### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JoshCheek** [SeanGallen/Project_Notes#7]
- Make sure tests pass every time you push / commit
- In the require statement for open3,
  Ruby filenames are lowercase, it currently works
  because the mac filesystem is case insensitive,
  but won't necessarily work everywhere
  
  So change:
  
  ``` ruby
  require 'Open3'
  ```
  
  to
  
  ``` ruby
  require 'open3'
  ```
- Pry in these situations:
  - wherever you are confused
    (ie what's going on in there?)
  - just before a failing test
    or exploding line
- The string expectation in the acceptance test
  is fragile. Use a regular expression instead:
  
  Change:
  
  ``` ruby
  expected = "...big fragile string..."
  assert_equal expected, stdout
  ```
  
  To:
  
  ``` ruby
  expected = /1 less than 2    1 < 2  # => true/
  assert_match expected, stdout
  ```
- Now that we have a regex, we can
  use the things regexes provide, like
  saying that we don't care how many spaces
  are between the description and the note.
  
  So we'll change:
  
  ``` ruby
  expected = /1 less than 2    1 < 2  # => true/
  ```
  
  To:
  
  ``` ruby
  expected = /1 less than 2 *1 < 2  # => true/
  ```

**Comment by matthewswan** [comment]
- Get rid of the unused string in the acceptance test
- The output of the notes program has weird indentation, modify your regexp to make it fail until the indentation is correct.
- Move the code from bin into lib
- All `puts` statements, `ARGV`, etc, stay in bin. All logic about how to select notes, goes into `lib`. The set of notes to test against goes into bin (ie you want to be able to provide simple easy notes when you test). The instantiation of your class goes in bin.
- Move away from the String representation. Its only value was on iteration 1 and 2, and it will make everything else complex.

Suggestion:
- Think about what tests you want to write... probably something like "if I have two notes, I can find the first one, I can find the second one, I can find both of them, I can find neither of them" (ie how would you prove to yourself that it actually worked). Then think about the easiest way to say those things. Then write a test that does that... Then write the code that makes it work. In other words, avoid trying to concoct grand sophisticated design, just stick with what is simple and can accomodate our current needs, with some ability to grow, going forward.
